name: Build AppImage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
        env:
          ACTIONS_STEP_DEBUG: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common klayout
          wget -O appimage-builder-x86_64.AppImage https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage
          chmod +x appimage-builder-x86_64.AppImage
          sudo mv appimage-builder-x86_64.AppImage /usr/local/bin/appimage-builder

      - name: Build AppImage
        run: |
          ls -l
          appimage-builder --recipe klayout_AppImageBuilder.yaml > build.log 2>&1
          cat build.log

      - name: Upload AppImage to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}